// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdL5a90nVGR8AgMtVBwc0GRzzDmk0-5cU',
    appId: '1:580067108605:web:380fc6dabde31516bb0094',
    messagingSenderId: '580067108605',
    projectId: 'flutterapp-17306',
    authDomain: 'flutterapp-17306.firebaseapp.com',
    storageBucket: 'flutterapp-17306.firebasestorage.app',
    measurementId: 'G-GZPH8G86NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREo7Z3CqiaffFEQ4XjbrgSVEi39di35M',
    appId: '1:580067108605:android:ed2d34d6f6b2bac2bb0094',
    messagingSenderId: '580067108605',
    projectId: 'flutterapp-17306',
    storageBucket: 'flutterapp-17306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0CGy5yCvt0DB5Sbx092jbsidYDaKbrLs',
    appId: '1:580067108605:ios:d44ddde0d9ccf857bb0094',
    messagingSenderId: '580067108605',
    projectId: 'flutterapp-17306',
    storageBucket: 'flutterapp-17306.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0CGy5yCvt0DB5Sbx092jbsidYDaKbrLs',
    appId: '1:580067108605:ios:d44ddde0d9ccf857bb0094',
    messagingSenderId: '580067108605',
    projectId: 'flutterapp-17306',
    storageBucket: 'flutterapp-17306.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdL5a90nVGR8AgMtVBwc0GRzzDmk0-5cU',
    appId: '1:580067108605:web:48c5b49f1daf21cebb0094',
    messagingSenderId: '580067108605',
    projectId: 'flutterapp-17306',
    authDomain: 'flutterapp-17306.firebaseapp.com',
    storageBucket: 'flutterapp-17306.firebasestorage.app',
    measurementId: 'G-Q84WN2DGCG',
  );
}
